# Generated by Django 3.0.5 on 2020-05-15 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='board',
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_started', models.BooleanField(default=False)),
                ('board', models.TextField(default='')),
                ('room', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='room.Room')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
