# Generated by Django 3.0.5 on 2020-04-26 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20200426_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='room',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.Room'),
        ),
    ]
