# Generated by Django 3.0.5 on 2020-04-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20200426_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='token',
            field=models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000', max_length=64),
        ),
    ]
